
void setRegMCP9804 ( UINT8 reg, UINT8 MSB , UINT8 LSB );

void setConfRegMCP9804 ( UINT8 MSB , UINT8 LSB );

void setTempUpperRegMCP9804 ( UINT8 MSB , UINT8 LSB );

void setTempLowerRegMCP9804 ( UINT8 MSB , UINT8 LSB);

void setTempCriticRegMCP9804 ( UINT8 MSB , UINT8 LSB);

void initRegMCP9804 ( UINT8 CONFMSB , UINT8 CONFLSB , UINT8 TUPMSB , UINT8 TUPLSB,UINT8 TLOWMSB , UINT8 TLOWLSB,
                     UINT8 TCRITMSB , UINT8 TCRITLSB);